---
tenants:
  - name: MY_FABRIC
    vrfs:
      - name: default
        vrf_id: 10
        svis:
          - id: 10
            name: 'Ten'
            tags: [ "Web" ]
            enabled: true
            ip_virtual_router_addresses:
              - 10.10.10.1
            nodes:
              - node: spine1
                ip_address: 10.10.10.2/24
              - node: spine2
                ip_address: 10.10.10.3/24
          - id: 20
            name: 'Twenty'
            tags: [ "App" ]
            enabled: true
            ip_virtual_router_addresses:
              - 10.20.20.1
            nodes:
              - node: spine1
                ip_address: 10.20.20.2/24
              - node: spine2
                ip_address: 10.20.20.3/24