---
- name: Deploy fabric to CVP
  hosts: FABRIC
  gather_facts: false
  tasks:
    - name: Provision CVP with AVD configuration
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 192.168.0.5
        cv_username: "{{ hostvars['cvp1'].ansible_user }}"  
        cv_password: "{{ hostvars['cvp1'].ansible_password }}"  
        cv_verify_certs: false
        configlets_prefix: 'AVD'
        # apply_mode: strict # Don't use this unless AVD is the only source of configlets
        state: present
        execute_tasks: false # Set to true if you want the change to be made without a change control approval
        cv_collection: v3
